apiVersion: v1
kind: Service
metadata:
  labels:
    app: HitbitServer
  name: HitbitServer
spec:
  clusterIP: None
  ports:
    - port: 8081
  selector:
    app: HitbitServer
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: ambassador
  name: HitbitServer-ingress
spec:
  rules:
    - http:
        paths:
          - path: "/HitbitServer"
            backend:
              serviceName: HitbitServer
              servicePort: 8081
